# Generated by Django 5.2.14 on 2026-05-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва товару')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Слаг для URL')),
                ('description', models.TextField(blank=True, verbose_name='Опис товару')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (грн)')),
                ('image', models.ImageField(blank=True, upload_to='product_images/%Y/%m/%d', verbose_name='Зображення товару')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний (доступний у магазині)')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ('-created_at',),
            },
        ),
    ]
